export default [
  {
    key: "-M53cnDXHNj_GHvPVH6s",
    actors: "Maria Schneider, Joe Dallesandro, Danièle Gégauff, Sylvie Matton",
    awards: "N/A",
    boxoffice: "N/A",
    country: "France",
    director: "Jacques Rivette",
    dvd: "N/A",
    genre: "Crime, Drama",
    id: "6f0c5709-feb7-41fc-a8ea-d40227c53ad7",
    image:
      "https://m.media-amazon.com/images/M/MV5BN2EzY2FjODEtMzcxOS00YmI2LTgxZGYtNWUyYjM5YzE3MzNjXkEyXkFqcGdeQXVyMjQzMzQzODY@._V1_SX300.jpg",
    imdbid: "tt0085934",
    imdbrating: "6.9",
    imdbvotes: "386",
    language: "French, English",
    metascore: "N/A",
    plot:
      "Elizabeth sends telegrams to her old boyfriend Ben in NYC and to her younger sister Leo in Rome to join her in Paris, where she is selling her dead father's estate. When Ben and Leo arrive, a mysterious adventure begins.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BN2EzY2FjODEtMzcxOS00YmI2LTgxZGYtNWUyYjM5YzE3MzNjXkEyXkFqcGdeQXVyMjQzMzQzODY@._V1_SX300.jpg",
    production: "Roissy Films",
    rated: "Not Rated",
    ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.9/10",
      },
    ],
    released: "06 Apr 1983",
    response: "True",
    runtime: "160 min",
    timestamp: 1587068217369,
    title: "Merry-Go-Round",
    type: "movie",
    website: "N/A",
    writer:
      "Eduardo de Gregorio (scenario), Suzanne Schiffman (scenario), Jacques Rivette (scenario), Eduardo de Gregorio (dialogue)",
    year: "1981",
  },
  {
    key: "-M53cbMSTPr3xGrjLG1l",
    actors:
      "Nikolay Burlyaev, Valentin Zubkov, Evgeniy Zharikov, Stepan Krylov",
    awards: "2 wins.",
    boxoffice: "N/A",
    country: "Soviet Union",
    director: "Andrei Tarkovsky, Eduard Abalov",
    dvd: "24 Jul 2007",
    genre: "Drama, War",
    id: "b8e2d321-8013-4d06-9d64-299f6685bd73",
    image:
      "https://m.media-amazon.com/images/M/MV5BOWUxZTU2YTUtMTVjNy00MGU1LWJmYmQtMjE1MTgxYjVmMDZiXkEyXkFqcGdeQXVyNDE5MTU2MDE@._V1_SX300.jpg",
    imdbid: "tt0056111",
    imdbrating: "8.1",
    imdbvotes: "28,472",
    language: "Russian, German",
    metascore: "N/A",
    plot:
      "In WW2, twelve year old Soviet orphan Ivan Bondarev works for the Soviet army as a scout behind the German lines and strikes a friendship with three sympathetic Soviet officers.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BOWUxZTU2YTUtMTVjNy00MGU1LWJmYmQtMjE1MTgxYjVmMDZiXkEyXkFqcGdeQXVyNDE5MTU2MDE@._V1_SX300.jpg",
    production: "Shore International",
    rated: "Not Rated",
    ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.1/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "100%",
      },
    ],
    released: "27 Jun 1963",
    response: "True",
    runtime: "84 min",
    timestamp: 1587068168786,
    title: "Ivan's Childhood",
    type: "movie",
    website: "N/A",
    writer:
      'Vladimir Bogomolov (story "Ivan"), Vladimir Bogomolov (screenplay), Mikhail Papava (screenplay)',
    year: "1962",
  },
  {
    key: "-M53cKmvmrNz13hOvZHD",
    actors:
      "Margarita Terekhova, Oleg Yankovskiy, Filipp Yankovskiy, Ignat Daniltsev",
    awards: "N/A",
    boxoffice: "N/A",
    country: "Soviet Union",
    director: "Andrei Tarkovsky",
    dvd: "21 Mar 2000",
    genre: "Biography, Drama",
    id: "32d48d81-cb91-4ceb-b2dd-d857dba80970",
    image:
      "https://m.media-amazon.com/images/M/MV5BOGRiNDc0ZmMtZWVmNS00ZmRkLWEwNjQtODdmYTIyZGJjMjc5XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    imdbid: "tt0072443",
    imdbrating: "8.1",
    imdbvotes: "35,616",
    language: "Russian, Spanish",
    metascore: "N/A",
    plot:
      "A dying man in his forties remembers his past. His childhood, his mother, the war, personal moments and things that tell of the recent history of all the Russian nation.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BOGRiNDc0ZmMtZWVmNS00ZmRkLWEwNjQtODdmYTIyZGJjMjc5XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    production: "Mosfilm Studios",
    rated: "G",
    ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.1/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "100%",
      },
    ],
    released: "18 Jan 1978",
    response: "True",
    runtime: "107 min",
    timestamp: 1587068096815,
    title: "The Mirror",
    type: "movie",
    website: "N/A",
    writer: "Aleksandr Misharin, Andrei Tarkovsky",
    year: "1975",
  },
  {
    key: "-M53c2Pq7S2C3VN-5Rfl",
    actors: "Liv Ullmann, Erland Josephson, Gunnel Lindblom",
    awards: "Won 1 Golden Globe. Another 10 wins & 5 nominations.",
    country: "Sweden",
    director: "N/A",
    genre: "Drama",
    id: "e7ac2dde-8152-413c-99c5-bc660d6d7af3",
    image:
      "https://m.media-amazon.com/images/M/MV5BNGU2NzA1MzktZjM3ZS00MThmLTg3OGUtNWE2NGI3Mjg1MzI4XkEyXkFqcGdeQXVyNjk0Nzc2MDY@._V1_SX300.jpg",
    imdbid: "tt0070644",
    imdbrating: "8.4",
    imdbvotes: "13,986",
    language: "Swedish",
    metascore: "N/A",
    plot: "Ten years within the marriage of Marianne and Johan.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BNGU2NzA1MzktZjM3ZS00MThmLTg3OGUtNWE2NGI3Mjg1MzI4XkEyXkFqcGdeQXVyNjk0Nzc2MDY@._V1_SX300.jpg",
    rated: "PG",
    ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.4/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "89%",
      },
    ],
    released: "11 Apr 1973",
    response: "True",
    runtime: "283 min",
    timestamp: 1587068021546,
    title: "Scenes from a Marriage",
    totalseasons: "1",
    type: "series",
    writer: "N/A",
    year: "1973",
  },
  {
    key: "-M53bsPA7nXnOIemd7Xy",
    actors:
      "Maren Schumacher, Cornelia Schmaus, Martina Servatius, Margot Busse",
    awards: "N/A",
    boxoffice: "N/A",
    country: "East Germany",
    director: "Ursula Bonhoff",
    dvd: "N/A",
    genre: "Drama",
    id: "0f00f876-2822-4b93-b86a-9c7fd335c916",
    image: "N/A",
    imdbid: "tt1092371",
    imdbrating: "N/A",
    imdbvotes: "N/A",
    language: "German",
    metascore: "N/A",
    plot: "N/A",
    poster: "N/A",
    production: "N/A",
    rated: "N/A",
    released: "20 Apr 1984",
    response: "True",
    runtime: "N/A",
    timestamp: 1587067976432,
    title: "Lebenszeichen",
    type: "movie",
    website: "N/A",
    writer: "Anne Dessau",
    year: "1984",
  },
  {
    key: "-M51sQzdMLri5k9BMUdl",
    actors:
      "Alisa Freyndlikh, Aleksandr Kaydanovskiy, Anatoliy Solonitsyn, Nikolay Grinko",
    awards: "2 wins & 2 nominations.",
    boxoffice: "$268,101",
    country: "Soviet Union",
    director: "Andrei Tarkovsky",
    dvd: "15 Oct 2002",
    genre: "Drama, Sci-Fi",
    id: "071e6fcb-15e1-47e0-aa20-167291efc35f",
    image:
      "https://m.media-amazon.com/images/M/MV5BMDgwODNmMGItMDcwYi00OWZjLTgyZjAtMGYwMmI4N2Q0NmJmXkEyXkFqcGdeQXVyNzY1MTU0Njk@._V1_SX300.jpg",
    imdbid: "tt0079944",
    imdbrating: "8.2",
    imdbvotes: "105,281",
    language: "Russian",
    metascore: "N/A",
    plot:
      "A guide leads two men through an area known as the Zone to find a room that grants wishes.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMDgwODNmMGItMDcwYi00OWZjLTgyZjAtMGYwMmI4N2Q0NmJmXkEyXkFqcGdeQXVyNzY1MTU0Njk@._V1_SX300.jpg",
    production: "Zweites Deutsches Fernsehen",
    rated: "Not Rated",
    ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.2/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "100%",
      },
    ],
    released: "17 Apr 1980",
    response: "True",
    runtime: "162 min",
    timestamp: 1587038762090,
    title: "Stalker",
    type: "movie",
    website: "N/A",
    writer:
      "Arkadiy Strugatskiy (novel), Boris Strugatskiy (novel), Arkadiy Strugatskiy (screenplay), Boris Strugatskiy (screenplay)",
    year: "1979",
  },
  {
    key: "-M4yHx32a69LM-aMayEL",
    actors: "Takeshi Kitano, Tadanobu Asano, Michiyo Yasuda, Taka Guadalcanal",
    awards: "24 wins & 14 nominations.",
    boxoffice: "$584,553",
    country: "Japan",
    director: "Takeshi Kitano",
    dvd: "09 Nov 2004",
    genre: "Action, Comedy, Crime, Drama, Thriller",
    id: "8ee9bd55-ad53-40d5-bf8b-2c3b1ff7a640",
    image:
      "https://m.media-amazon.com/images/M/MV5BOTQ2MzNmZDYtZDExNi00MDA2LWFkNjYtY2I4N2E4NzkzOTEwXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    imdbid: "tt0363226",
    imdbrating: "7.5",
    imdbvotes: "45,773",
    language: "Japanese",
    metascore: "75",
    plot:
      "The blind masseur/swordsman comes to a town in control of warring gangs, and while bunking with a farming family, he meets two women with their own agenda.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BOTQ2MzNmZDYtZDExNi00MDA2LWFkNjYtY2I4N2E4NzkzOTEwXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    production: "Miramax Films",
    rated: "R",
    ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.5/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "87%",
      },
      {
        Source: "Metacritic",
        Value: "75/100",
      },
    ],
    released: "06 Sep 2003",
    response: "True",
    runtime: "116 min",
    timestamp: 1586961829661,
    title: "The Blind Swordsman: Zatoichi",
    type: "movie",
    website: "N/A",
    writer: "Takeshi Kitano (screenplay), Kan Shimozawa (novels)",
    year: "2003",
  },
  {
    key: "-M4xnBlEIGrtZ70ksGMq",
    actors: "Jennifer Jason Leigh, Jude Law, Ian Holm, Willem Dafoe",
    awards: "3 wins & 13 nominations.",
    boxoffice: "N/A",
    country: "UK, France, Canada",
    director: "David Cronenberg",
    dvd: "19 Oct 1999",
    genre: "Horror, Sci-Fi, Thriller",
    id: "72e54bed-9f9c-4121-bca0-074817f8082e",
    image:
      "https://m.media-amazon.com/images/M/MV5BMmU1MTJkYWItMzM5Ny00NDgxLTgxOGEtNTkzNDdkZjkwNGI0XkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg",
    imdbid: "tt0120907",
    imdbrating: "6.8",
    imdbvotes: "90,364",
    language: "English",
    metascore: "68",
    plot:
      "A game designer on the run from assassins must play her latest virtual reality creation with a marketing trainee to determine if the game has been damaged.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMmU1MTJkYWItMzM5Ny00NDgxLTgxOGEtNTkzNDdkZjkwNGI0XkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg",
    production: "Miramax",
    rated: "R",
    ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.8/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "74%",
      },
      {
        Source: "Metacritic",
        Value: "68/100",
      },
    ],
    released: "23 Apr 1999",
    response: "True",
    runtime: "97 min",
    timestamp: 1586953505355,
    title: "eXistenZ",
    type: "movie",
    website: "N/A",
    writer: "David Cronenberg",
    year: "1999",
  },
  {
    key: "-M4xmJAVuk6DFCIsgCO4",
    actors: "Nicolas Cage, Laura Dern, Willem Dafoe, J.E. Freeman",
    awards: "Nominated for 1 Oscar. Another 4 wins & 10 nominations.",
    boxoffice: "N/A",
    country: "USA",
    director: "David Lynch",
    dvd: "07 Dec 2004",
    genre: "Comedy, Crime, Drama, Thriller",
    id: "e9c605e0-3f1b-446c-bbbe-962363fc5263",
    image:
      "https://m.media-amazon.com/images/M/MV5BMjAxYmJhMTMtNmZlZi00ZWJlLTlmMjctOTg5ZTg4MzZmOWM2XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    imdbid: "tt0100935",
    imdbrating: "7.2",
    imdbvotes: "78,415",
    language: "English, Spanish",
    metascore: "52",
    plot:
      "Young lovers Sailor and Lula run from the variety of weirdos that Lula's mom has hired to kill Sailor.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMjAxYmJhMTMtNmZlZi00ZWJlLTlmMjctOTg5ZTg4MzZmOWM2XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    production: "Media Home Entertainment",
    rated: "R",
    ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.2/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "65%",
      },
      {
        Source: "Metacritic",
        Value: "52/100",
      },
    ],
    released: "17 Aug 1990",
    response: "True",
    runtime: "125 min",
    timestamp: 1586953273564,
    title: "Wild at Heart",
    type: "movie",
    website: "N/A",
    writer: "Barry Gifford (novel), David Lynch (screenplay)",
    year: "1990",
  },
  {
    key: "-M4xmB1trUyyjP-6FAP-",
    actors: "Ewan McGregor, Albert Finney, Billy Crudup, Jessica Lange",
    awards: "Nominated for 1 Oscar. Another 68 nominations.",
    boxoffice: "$66,257,002",
    country: "USA",
    director: "Tim Burton",
    dvd: "27 Apr 2004",
    genre: "Adventure, Drama, Fantasy, Romance",
    id: "f2b82537-aaec-471e-a28d-5aa1037b770a",
    image:
      "https://m.media-amazon.com/images/M/MV5BMmU3NzIyODctYjVhOC00NzBmLTlhNWItMzBlODEwZTlmMjUzXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg",
    imdbid: "tt0319061",
    imdbrating: "8.0",
    imdbvotes: "399,410",
    language: "English, Cantonese",
    metascore: "58",
    plot:
      "A frustrated son tries to determine the fact from fiction in his dying father's life.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMmU3NzIyODctYjVhOC00NzBmLTlhNWItMzBlODEwZTlmMjUzXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg",
    production: "Sony Pictures",
    rated: "PG-13",
    ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.0/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "75%",
      },
      {
        Source: "Metacritic",
        Value: "58/100",
      },
    ],
    released: "09 Jan 2004",
    response: "True",
    runtime: "125 min",
    timestamp: 1586953240245,
    title: "Big Fish",
    type: "movie",
    website: "N/A",
    writer: "Daniel Wallace (novel), John August (screenplay)",
    year: "2003",
  },
  {
    key: "-M4xH8Nnw78HnSvGP-f3",
    actors: "James Spader, Holly Hunter, Elias Koteas, Deborah Kara Unger",
    awards: "9 wins & 5 nominations.",
    boxoffice: "$3,168,660",
    country: "Canada",
    director: "David Cronenberg",
    dvd: "17 Nov 1998",
    genre: "Drama",
    id: "8414bb32-ef0d-4f63-812b-2d2a7376cac1",
    image:
      "https://m.media-amazon.com/images/M/MV5BZjlhMDBlNDQtMjZkZi00NzJmLWI4MTgtZDdkMzZmZDcyZGNmXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    imdbid: "tt0115964",
    imdbrating: "6.4",
    imdbvotes: "49,249",
    language: "English, Swedish",
    metascore: "47",
    plot:
      "After getting into a serious car accident, a TV director discovers an underground sub-culture of scarred, omnisexual car-crash victims who use car accidents and the raw sexual energy they produce to try to rejuvenate his sex life with his wife.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BZjlhMDBlNDQtMjZkZi00NzJmLWI4MTgtZDdkMzZmZDcyZGNmXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    production: "Fine Line Features",
    rated: "NC-17",
    ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.4/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "59%",
      },
      {
        Source: "Metacritic",
        Value: "47/100",
      },
    ],
    released: "21 Mar 1997",
    response: "True",
    runtime: "100 min",
    timestamp: 1586944840789,
    title: "Crash",
    type: "movie",
    website: "N/A",
    writer: "J.G. Ballard (novel), David Cronenberg",
    year: "1996",
  },
  {
    key: "-M4xGZ3dtBDKt9PN3Xcs",
    actors: "Yeong-su Oh, Ki-duk Kim, Young-min Kim, Jae-kyeong Seo",
    awards: "15 wins & 8 nominations.",
    boxoffice: "$2,105,230",
    country: "South Korea, Germany",
    director: "Ki-duk Kim",
    dvd: "07 Sep 2004",
    genre: "Drama, Romance",
    id: "84b516b7-0086-41e6-8bd2-e09cb48aae2a",
    image:
      "https://m.media-amazon.com/images/M/MV5BMTI0ODMwOTIxOV5BMl5BanBnXkFtZTcwMzE2NDUyMQ@@._V1_SX300.jpg",
    imdbid: "tt0374546",
    imdbrating: "8.0",
    imdbvotes: "73,601",
    language: "Korean",
    metascore: "85",
    plot:
      "A boy is raised by a Buddhist monk on an isolated floating temple where the years pass like the seasons.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMTI0ODMwOTIxOV5BMl5BanBnXkFtZTcwMzE2NDUyMQ@@._V1_SX300.jpg",
    production: "Sony Pictures Classics",
    rated: "R",
    ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.0/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "94%",
      },
      {
        Source: "Metacritic",
        Value: "85/100",
      },
    ],
    released: "28 May 2004",
    response: "True",
    runtime: "103 min",
    timestamp: 1586944687957,
    title: "Spring, Summer, Fall, Winter... and Spring",
    type: "movie",
    website: "N/A",
    writer: "Ki-duk Kim",
    year: "2003",
  },
];
